# Generated by Django 5.0.3 on 2024-03-09 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarDekho_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlist',
            name='showroom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Showrooms', to='CarDekho_app.showroomlist'),
            preserve_default=False,
        ),
    ]
